abstract: Change text containing HTML into a formatted HTML fragment
author: Andrew Sterling Hanenkamp, C<< <hanenkamp@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: HTML-ParagraphSplit
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires: 
  HTML::Entities: 0
  HTML::Tagset: 0
  HTML::TreeBuilder: 0
  Module::CoreList: 0
version: 1.05
